---
title: "<center><font aspan size = '6'>Mutate column in data.frame with some NA values</font></center>"
author: "<center>Wyclife Agumba Oluoch wyclifeoluoch@gmail.com</center>"
date: "<center>`r Sys.time()`</center>"
output: 
  github_document: default
bibliography: packages.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("dplyr",
              'base',
              'knitr',
              'rmarkdown')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> 
  invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'packages.bib')
```

# Introduction

```{r NA}
x <- data.frame(column = c(1:5, NA, 9, NA, 14, NA))
x_mutated <- x |> mutate(mutated = case_when(column <= 5 ~ 'Small', column > 5 ~ 'Big', column |> is.na() ~ 'This is NA'))
kable(x_mutated)
```

# References

